Question Dialog - 수정 모드 삭제 & Review Dialog - 기존에 존재하던 버그 수정
Liberty52/admin-page pull request #100
Opened 2023-10-12 17:35 UTC by DryRains

**Question Dialog - 수정 모드 삭제**
<img width="917" alt="스크린샷 2023-10-13 오전 2 02 24" src="https://github.com/Liberty52/admin-page/assets/96376539/57e63255-68bf-4254-8d98-8ab7c56d30de">

Review Dialog - 기존에 존재하던 버그 수정
1. Review Dialog 조회 시 에러
2. Review Dialog에서 텍스트 변화 없이 수정하는 건에 대해 막지 않는 문제

<수정 전>
![old](https://github.com/Liberty52/admin-page/assets/96376539/4a3649b7-ec21-4ccc-adf5-29bddbe5c314)

<수정 후>
![%E1%84%92%E1%85%AA%E1%84%86%E1%85%A7%E1%86%AB%20%E1%84%80%E1%85%B5%E1%84%85%E1%85%A9%E1%86%A8%202023-10-13%20%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A5%E1%86%AB%2012 20 25](https://github.com/Liberty52/admin-page/assets/96376539/69601335-93ed-462a-bf09-1ac16a1a6e79)

2023-10-16 02:33 UTC, Autumn-Rainfall approved these changes
고생하셨습니다!

2023-10-16 08:56 UTC, 2hanbyeol1 requested changes
"ADD", "EDIT" 같은 문자열은 하단 링크처럼 constants로 관리하는 것이 어떨까요??

https://github.com/Liberty52/admin-page/blob/main/src/constants/mode.js

2023-10-16 15:42 UTC, DryRains commented
> "ADD", "EDIT" 같은 문자열은 하단 링크처럼 constants로 관리하는 것이 어떨까요??
> 
> https://github.com/Liberty52/admin-page/blob/main/src/constants/mode.js

수정했습니다!!

2023-10-16 23:44 UTC, KimHyeongKeun commented
고생하셨습니다

2023-10-17 12:03 UTC, 2hanbyeol1 approved these changes

2023-10-17 12:05 UTC, merged