[LIB-100] 상품 추가, 조회
Liberty52/admin-page pull request #116
Opened 2023-10-21 18:40 UTC by KimHyeongKeun

- 상품 추가
<img width="1434" alt="스크린샷 2023-10-22 오전 3 35 02" src="https://github.com/Liberty52/admin-page/assets/107840065/a347d010-e835-4789-82f2-b4750f9fd310">

- 상품 조회
<img width="1440" alt="스크린샷 2023-10-22 오전 3 35 52" src="https://github.com/Liberty52/admin-page/assets/107840065/0d6f10f9-6ee4-46a3-9633-2a4e77738f79">

: 상품 추가하고 상품 정보를 조회하는 기능

2023-10-22 07:24 UTC, heeeione requested changes
확인부탁드립니다

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +    // }
주석은 지우는 게 좋습니다.

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +          label="작가 이름"
여긴 작품 이름 아닌 가요 ??
name값에 artName 있어서요
위의 TextField가 작가 이름 같습니다

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +            value={artistName}
여기도 name이랑 value가 안 맞는 것 같습니다

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +           label="작가 이름"
여기도요

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    const change = (value) => {
뭘 change 해주는 지 함수명을 좀 더 구체적으로 써주면 좋을 것 같습니다

2023-10-22 07:24 UTC, heeeione commented on src/component/license/LicenseTable.js
> +  })
state가 바뀔 때마다 화면이 렌더링 될텐데
의도하신 바가 맞나요 ??

2023-10-22 08:15 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +    // }
넵 알겠습니다

2023-10-22 08:16 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +          label="작가 이름"
name과 label 맞추었습니다.

2023-10-22 08:16 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +            value={artistName}
똑같이 name과 label 맞추었습니다.

2023-10-22 08:16 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +           label="작가 이름"
넵 알겠습니다

2023-10-22 08:17 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    const change = (value) => {
icCustomChange함수명으로 변경하였습니다

2023-10-22 08:17 UTC, KimHyeongKeun commented on src/component/license/LicenseTable.js
> +  })
,[]를 추가하였습니다!

2023-10-22 09:32 UTC, jungyeons approved these changes

2023-10-22 10:56 UTC, heeeione requested changes
확인부탁드립니다

2023-10-22 10:56 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
저번에도 얘기했지만 여러 state로 나누어서 관리하면 이점이 있나요 ??
있다면 무엇인지 궁금합니다.

저번에는 안 나누면 등록이나 수정이 안 된다고 하셨던 것 같은데
안 되는 이유도 궁금합니다.

2023-10-22 10:56 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    }
이게 무엇을 하는 코드인가요 ??

2023-10-22 10:56 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    const stateRe = (value) => {
함수 이름이 무엇을 의미하는 건지 잘 모르겠어요

2023-10-22 11:11 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
그냥 데이터를 setData를 하면 데이터 안에 여러 개의 값이 있어서   set으로 받아지지 않아서 각각으로 나눠서 하였습니다

2023-10-22 11:11 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
value가 string 타입으로 각각 나누어서 boolean값으로 리턴하는 것입니다

2023-10-22 11:11 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    const stateRe = (value) => {
StateEnglish로 함수 이름 변경하였습니다.

2023-10-22 12:12 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    }
value의 대소문자를 필터링하는건가요 ??

2023-10-22 12:13 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
따로 뺀 state랑 data state의 객체의 key랑 같은 것 같은데 어떤 게 문제가 되는 건가요 ??

2023-10-22 12:26 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
따로 뺀 state는 data 객체의 key하나를 담았는데 setData는 data 객체 전체를 받아들여서 인식을 못하는 것 같습니다

2023-10-22 12:27 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
처음에 String값인지를 판단하고 그 다음에 대문자가 있는 경우 소문자로 필터링 후 참, 거짓을 반환합니다

2023-10-23 01:44 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
key의 개수가 문제가 되나요 ??
문제가 된다면 어떤 문제인지 궁금합니다

2023-10-23 01:44 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    }
대문자일때 false를 해주는 이유는 뭔가요 ??

2023-10-23 02:00 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
키의 개수가 아니라 setData로 받으면  키의 네이밍을 찾아가지 못해 생기는 문제라고 생각하여 state마다 나누어서 하였습니다.

2023-10-23 02:01 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
대문자일때 false가 아니라 영어 문자를 소문자로 바꾸었을 때 "false"랑 같을 시 boolean false를 리턴하는 것입니다.

2023-10-23 02:02 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
참,거짓을 판단하기 위해 사용하였습니다

2023-10-23 02:16 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    }
이게 필요한 이유가 뭔가요 ??

2023-10-23 02:20 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
setData(prevData)하고

onChange에서 input의 e.target.name과 value를 매핑시켜주면 되지 않나요 ??

2023-10-23 02:51 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
저는  전에 희원님도 보셨지만  처음에 setData(prevData)에서 먼저 에러가 납니다. 나중에 이름과 매핑하기 전에 먼저 setData에서 문제가 발생해서 저는 따로 state를 나누어서 하였습니다

2023-10-23 02:53 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
에러 내용이 뭐였죠 ??

2023-10-23 02:58 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
isCustom을 참, 거짓을 판단하기 위해서 사용하였는데 저는 혹시 대문자가 들어올 경우를 생각해서 toLowerCase를 적용하였는데 필요없다고 생각하시면 지우겠습니다.

2023-10-23 03:03 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
PUT에서 
// Send the request
    request.send(requestData || null);
에러입니다

2023-10-24 04:25 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +        setArtistName(prevData.artistName);
에러를 해결하기 위해서 state를 늘리는 건 좋은 방법이 아닌 것 같습니다

2023-10-24 04:26 UTC, heeeione commented on src/component/license/LicenseOption.js
> +    }
Custom에 대문자가 들어가면 에러가 발생하나요 ??

2023-10-24 04:48 UTC, heeeione approved these changes
데모까지 얼마 남지 않아서 approve하지만 데모 끝난 후에 refactoring 해주세요

2023-10-24 05:01 UTC, KimHyeongKeun commented on src/component/license/LicenseOption.js
> +    }
true, false가 소문자여서 대문자가 들어오면 에러가 발생하여 소문자 처리하도록 하였는데 toLowerCase 부분은 삭제하였습니다.

2023-10-24 05:03 UTC, merged