[LIB-127]라이선스 옵션 CRU
Liberty52/admin-page pull request #140
Opened 2023-11-08 08:18 UTC by KimHyeongKeun

라이선스 추가, 조회
<img width="1437" alt="스크린샷 2023-11-08 오후 4 20 30" src="https://github.com/Liberty52/admin-page/assets/107840065/cf87b6ac-b59b-4a20-8552-c214b3d09ee8">

라이선스 옵션 수정
-현재 수정 완료 후 옵션 날짜 조회 부분 date 안불러옴 -> 수정예정

<img width="1433" alt="스크린샷 2023-11-08 오후 4 23 13" src="https://github.com/Liberty52/admin-page/assets/107840065/1a732445-e2ad-4f05-8afa-f77d72449370">

2023-11-08 08:51 UTC, jungyeons approved these changes

2023-11-08 08:54 UTC, merged

2023-11-08 08:55 UTC, heeeione requested changes
데모까지 얼마 안 남아서 일단 눈에 보이는 것만 코멘트 했습니다
앞으로는 먼저 pr 올려주시고 wip라벨 붙여주세요
그러면 제가 천천히 보면서 피드백 드릴게요

2023-11-08 08:55 UTC, heeeione commented on src/axios/License.js
> +}
안 쓰는 건 지웁시다

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +    console.log(image);
콘솔도 지웁시다

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +                  // onChange={(e) => textChangeArtistName(e)}
주석도 지웁시다

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +                  // onChange={(e) => textChangeArtName(e)}
여기도

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +                  // onChange={(e) => textChangeStock(e)}
여기도

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +                    // value={dayjs(startDate)}
여기도

2023-11-08 08:55 UTC, heeeione commented on src/component/license/LicenseDialog.js
> +                    // value={dayjs(endDate)}
여기도

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionDetailModal.js
> +  const [endDate, setEndDate] = useState('');
아무리 생각해도 해당 부분은 이해가 되지 않습니다
객체 형태의 state 하나로 관리하면 유지보수하기 좋을 것 같은데 이렇게 하는 건 좋은 방법이 아닌 것 같습니다

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionDetailModal.js
> +    setButtonText(mode === ModalMode.ADD ? '추가하기' : '수정하기');
위에 했던 코멘트와 같은 맥락으로 만약에 관리해야할 state가 늘어나거나 준다면 해당 state를 다 찾아서 수정해야하니까
유지보수하기 좋지 않다고 생각합니다

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionDetailModal.js
> +  }
혹시 prettier 적용이 안 되시나요??

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionModal.js
> +  const [value, setValue] = useState('');
무슨 value인지 적어주시면 좋을 것 같습니다

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionModal.js
> +          </Grid> */}
주석은 지웁시다

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionPanel.js
> +  const [licenseOptionDetailModalOpen, setLicenseOptionDetailModalOpen] = useState(false);
const [licenseOptionModalOpen, setLicenseOptionModalOpen] = useState(false); 라인과 다른 점은 뭔가요??

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionPanel.js
> +      console.log(response.data);
콘솔 로그는 지웁시다

2023-11-08 08:55 UTC, heeeione commented on src/component/product/LicenseOptionPanel.js
> +    console.log("id??"+licenseOption.licenseOptionId);
여기도요

2023-11-08 08:56 UTC, KimHyeongKeun commented on src/axios/License.js
> +}
넵 알겠습니다

2023-11-08 08:57 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +    console.log(image);
넵 알겠습니다

2023-11-14 13:11 UTC, KimHyeongKeun commented on src/component/product/LicenseOptionPanel.js
> +      console.log(response.data);
넵 알겠습니다

2023-11-14 13:11 UTC, KimHyeongKeun commented on src/component/product/LicenseOptionModal.js
> +          </Grid> */}
넵 알겠습니다

2023-11-14 13:11 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +                  // onChange={(e) => textChangeArtistName(e)}
넵 알겠습니다

2023-11-14 13:11 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +                  // onChange={(e) => textChangeStock(e)}
넵 알겠습니다

2023-11-14 13:12 UTC, KimHyeongKeun commented on src/component/product/LicenseOptionPanel.js
> +    console.log("id??"+licenseOption.licenseOptionId);
넵

2023-11-14 13:14 UTC, KimHyeongKeun commented on src/component/product/LicenseOptionPanel.js
> +  const [licenseOptionDetailModalOpen, setLicenseOptionDetailModalOpen] = useState(false);
licenseOptionModalOpen은 라이선스 옵션 관리에서  라이선스 옵션 추가 버튼으로 나타나는 모달이고 licenseOptionDetailModalOpen은 라이선스 옵션이 생긴 후에 디테일을 추가하는 부분의 모달입니다!

2023-11-14 13:14 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +                    // value={dayjs(startDate)}
넵

2023-11-14 13:14 UTC, KimHyeongKeun commented on src/component/license/LicenseDialog.js
> +                    // value={dayjs(endDate)}
넵!

2023-11-14 13:18 UTC, KimHyeongKeun commented on src/component/product/LicenseOptionDetailModal.js
> +  }
이번에 적용돼서 사옹하였습니다!