[관리자] License Table Update기능
Liberty52/admin-page pull request #141
Opened 2023-11-08 13:04 UTC by jungyeons

# [관리자] License Table Update기능 

## < 수정 전 화면>
![수정 전](https://github.com/Liberty52/admin-page/assets/81145288/ad6b7f38-91f4-421d-8a06-a6d498d58bce)

## < 내용 수정>
![내용 수정](https://github.com/Liberty52/admin-page/assets/81145288/ca9bc099-1a1d-402e-9863-b5f834bdaba5)

- 희원님께서 도움주셔서 수정 화면은 해결 완료 했습니다 ~

2023-11-09 06:32 UTC, heeeione requested changes

2023-11-09 06:32 UTC, heeeione commented on src/component/license/LicenseTable.js
> +  }, [state, custom]);
위의 useEffect에도 check 함수를 실행시키는데
여기서도 실행시키는 이유가 있나요???
dependency도 같은데

2023-11-09 06:32 UTC, heeeione commented on src/component/license/LicenseTable.js
> +  const check = () => {
어떤 걸 check 하는지 좀 더 직관적으로 쓰는 게 좋습니다

2023-11-09 06:32 UTC, heeeione commented on src/component/license/LicenseTable.js
> +
prettier 적용이 안 되시나요??

2023-11-12 08:01 UTC, jungyeons commented on src/component/license/LicenseTable.js
> +  }, [state, custom]);
수정되어있더라구요 ! 감사합니다 ~

2023-11-12 08:01 UTC, jungyeons commented on src/component/license/LicenseTable.js
> +  const check = () => {
stateCheck으로 refactoring 하였습니다 ~

2023-11-12 08:02 UTC, jungyeons commented on src/component/license/LicenseTable.js
> +
수정해주신것 같더라구요 ! 감사합니다 ~

2023-11-13 01:58 UTC, heeeione commented on src/component/license/LicenseTable.js
> +  const check = () => {
state가 무슨 state인지 구체적으로 작성하는 게 좋습니다.
저기서 사용하는 state가 많으니까요

2023-11-13 02:15 UTC, jungyeons commented on src/component/license/LicenseTable.js
> +  const check = () => {
아 근데 저거 걱정안해도 될거같은게 저부분 삭제되서 괜찮을 것 같습니다 ~

2023-11-13 02:22 UTC, heeeione approved these changes
로컬에서 돌아간다면 머지하셔도 돼요

2023-11-13 02:25 UTC, jungyeons commented
> 로컬에서 돌아간다면 머지하셔도 돼요

넹 ~ 확인 해보고 잘 돌아가면 머지하겠습니다 ! 꼼꼼히 봐주셔서 감사해요 ~~

2023-11-13 02:27 UTC, merged